=== Tejasa1/ScalaNotes-Neustar/JsonReader/Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "PiiEncodingFormat": {
      "type": "string"
    },
    "BridgeDataType": {
      "type": "string"
    },
    "BridgeDataColumns": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "PublicKeyVersion": {
      "type": "string"
    },
    "BridgeSetHash": {
      "type": "string"
    },
    "BridgeProvider": {
      "type": "string"
    },
    "VersionId": {
      "type": "string"
    },
    "DataProvider": {
      "type": "string"
    }
  },
  "required": [
    "PiiEncodingFormat",
    "BridgeDataType",
    "BridgeDataColumns",
    "PublicKeyVersion",
    "BridgeSetHash",
    "BridgeProvider",
    "VersionId",
    "DataProvider"
  ]
}

=== Tejasa1/ScalaNotes-Neustar/JsonReader/File.json
{
  "PiiEncodingFormat": "BASE64-HMAC_SHA256",
  "BridgeDataType": "EMAIL",
  "BridgeDataColumns": [
    "BRIDGE_ID",
    "EMAIL"
  ],
  "PublicKeyVersion": "2015_09_15",
  "BridgeSetHash": "0ab67134110ad43535bd287b6da0754284d54064ef832ac07bb9bd7afe1e0151527b0d34802e43cef7505ea70abbee41e66ebf883846b5a5b13b3db10e2e3422",
  "BridgeProvider": "NEUSTAR",
  "VersionId": "neu_iri_e_20230105",
  "DataProvider": "IRI"
}

=== Tejasa1/ScalaNotes-Neustar/JsonReader/ChangedFile1.json
{
  "PiiEncodingFormat": "BASE64-HMAC_SHA256",
  "BridgeDataType": "EMAIL",
  "BridgeDataColumns": [
    "EMAIL",
    "BRIDGE_ID",
    "JJJJJ"
  ],
  "PublicKeyVersion": "2015_09_15",
  "BridgeSetHash": "0ab67134110ad43535bd287b6da0754284d54064ef832ac07bb9bd7afe1e0151527b0d34802e43cef7505ea70abbee41e66ebf883846b5a5b13b3db10e2e3422",
  "VersionId": "neu_iri_e_20230105",
  "BridgeProvider": "NEUSTAR",
  "DataProvider": "IRI"

}
